server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # Evita conflictos si Eureka registra en mayúsculas o minúsculas

      # Filtro GLOBAL: Inyecta el Trace ID único para la auditoría asíncrona con ms-logs
      # NOTA: '${random.uuid}' genera un ID estático al arrancar. Para producción, usar un GlobalFilter en código Java.
      default-filters:
        - AddRequestHeader=X-Trace-Id, ${random.uuid}

      routes:
        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/api/auth/**

        - id: ms-users
          uri: lb://ms-users
          predicates:
            - Path=/api/users/**

        - id: ms-logs
          uri: lb://ms-logs
          predicates:
            - Path=/api/logs/**
        
        # Enrutamiento hacia Gestión de Edificios
        - id: ms-buildings
          uri: lb://ms-buildings
          predicates:
            - Path=/api/edificios/**

        - id: ms-quotes
          uri: lb://ms-quotes
          predicates:
            - Path=/api/cotizaciones/**

        - id: ms-security
          uri: lb://ms-security
          predicates:
            - Path=/api/roles/**

        - id: ms-fleet
          uri: lb://ms-fleet
          predicates:
            - Path=/api/vehiculos/**

# El bloque de Eureka se hereda del global (application.yml), pero mantenemos lo específico del host de red
eureka:
  instance:
    hostname: brm-api-gateway

# Monitoreo Actuator para verificación de mallas distribuidas
management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true # Habilita la inspección de rutas activas vía /actuator/gateway/routes

# CORREGIDO: Eliminadas las trazas de Hibernate para evitar el colapso de Spring WebFlux
logging:
  level:
    root: INFO
    com.logistica: DEBUG  # Permite ver el enrutamiento y filtros del Gateway
    org.springframework.cloud.gateway: DEBUG # Te dará visibilidad total de por dónde viajan las peticiones