server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # Recomendado para evitar errores de mayúsculas en las URLs
      
      # MEJORA: Filtro GLOBAL para todos los servicios (Genera un ID único por petición)
      default-filters:
        - AddRequestHeader=X-Trace-Id, ${random.uuid}

      routes:
      # 1. Seguridad y Autenticación (Prioridad 1 para el Login)
        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/api/auth/**

        # RUTA PARA USUARIOS (Activa)
        # Gestión de perfiles
        #- id: ms-users
        #  uri: lb://ms-users
        #  predicates:
        #    - Path=/api/users/**
        
        # --- SECCIÓN POR INTEGRAR (Comentados para evitar errores de 503 hasta que existan) ---
        # Solo debes quitar el '#' cuando el microservicio esté en ejecución en Docker

        # 3. Cerebro de Permisos (RBAC)
        #- id: service-security
        #  uri: lb://service-security
        #  predicates:
        #    - Path=/api/security/**

        # 4. Orquestador de Mapas y Geofencing
        #- id: ms-logistics
        #  uri: lb://ms-logistics
        #  predicates:
        #    - Path=/api/logistics/**

        # 5. Gestión de Reparaciones (Core)
        #- id: ms-workorders
        #  uri: lb://ms-workorders
        #  predicates:
        #    - Path=/api/workorders/**

        # 6. Auditoría de Trazabilidad (Función Especial)
        #- id: service-logs
        #  uri: lb://service-logs
        #  predicates:
        #    - Path=/api/logs/**

# Configuración de Cliente Eureka (Centralizada)
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true # Recomendado en Docker para evitar problemas de resolución de nombres
    hostname: api-gateway

# Actuator: Configuración para el monitoreo y healthcheck de Docker
management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true # Permite ver las rutas activas vía Actuator