server:
  port: ${PORT:8089}

spring:
  datasource:
    # Conectado a la base de datos unificada en su esquema de inventario
    url: jdbc:mysql://mysql-db:3306/db_service_inventory?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: app_user
    password: "1234"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # Parámetros específicos del flujo de mensajería de Inventario
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: inventory-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

# Telemetría avanzada unificada exclusiva para este módulo relacional
logging:
  level:
    com.logistica: DEBUG  # <-- Crucial para ver tus controladores e inventario
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.orm.results.graph.AST: TRACE
    org.hibernate.type.descriptor.jdbc.spi.JdbcTypeRegistry: TRACE