server:
  port: 8082 # <-- CORREGIDO: Volvemos al puerto 8082 original para evitar chocar con el Gateway

spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/db_service_logs?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: app_user
    password: "1234"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    consumer:
      group-id: logs-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    root: INFO
    com.logistica: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.orm.results.graph.AST: TRACE
    org.hibernate.type.descriptor.jdbc.spi.JdbcTypeRegistry: TRACE