server:
  port: 8085  # Puerto operativo estandarizado para ms-staff

spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/db_service_staff?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: app_user
    password: "1234"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# Toda la configuración base de Eureka e infraestructura de red se hereda limpiamente del global

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Telemetría avanzada unificada exclusiva para este módulo relacional
logging:
  level:
    root: INFO
    com.logistica: DEBUG  # Muestra el rastreo de asignaciones de personal y choferes
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.orm.results.graph.AST: TRACE
    org.hibernate.type.descriptor.jdbc.spi.JdbcTypeRegistry: TRACE