# 1. Identidad del Microservicio
# Este nombre es el que usará Eureka y Feign para encontrarlo
spring.application.name=ms-users

# 2. Puerto de ejecución
server.port=8082

# 3. Configuración de Base de Datos MySQL (db_pedidos)
# Asegúrate de haber creado la base de datos: CREATE DATABASE db_pedidos;
# Ejemplo para el Microservicio de Cotizaciones (Service-Quotes)
spring.datasource.url=jdbc:mysql://localhost:3306/db_users?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

# 4. Configuración de JPA / Hibernate
# 'update' crea las tablas automáticamente basadas en tu clase @Entity Pedido
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 5. Registro en el Servidor Eureka
# Aquí le decimos dónde está el "directorio" de microservicios
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Superimprotante activar estas configuraciones para evitar problemas al reconocer los servicios
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

# 6. Configuración de Feign (Opcional pero recomendada)
# Permite ver más detalles si falla la comunicación con ms-stock
logging.level.example.ms_pedidos.client.StockClient=DEBUG
